### ISSUE TITLE
Requesting access to earthindex Project on Google Cloud 

### ISSUE THREAD

**Issue by daxinqi** [earthrise-media/mining-detector#14]
Upon running the gee pipeline notebook I get this error:

```jupyter-notebook
 Caller does not have required permission to use project earthindex. Grant the caller the roles/serviceusage.serviceUsageConsumer role, or a custom role with the serviceusage.services.use permission, by visiting https://console.developers.google.com/iam-admin/iam/project?project=earthindex and then retry. Propagation of the new permission may take a few minutes.
``` 

Then I opened the Google Cloud Console link which led me to this error:

![Screenshot (177)](https://github.com/earthrise-media/mining-detector/assets/173593793/708005bf-c2d1-44c3-8e7d-28f4275ccd24)

Is there a way that I can get the necessary permissions for this project?

**Comment by eboyda** [comment]
To run the code you will need to establish your own project on Google Earth Engine and edit the project name accordingly.  Good luck!
